server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SheepEatLion/cloud_config_server
          default-label: main

# actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true